### ISSUE TITLE
How do I upgrade Amazon Cloud Player with Flatpak from script?

### ISSUE THREAD

**Issue by chuck-talk-sp** [tiliado/nuvola-repository-index#4]
I have a Tiliado account, but have not determined how to update amazon cloud player in the Nuvola apps from 5.5 to 5.6. Any ideas on how to upgrade that with Flatpak?

**Comment by fenryxo** [comment]
Hello @chuck-talk-sp. The commands are `flatpak update --user; flatpak update --system`. Does that work?

**Comment by fenryxo** [comment]
Closing as expired due to inactivity of the reporter.
