### ISSUE TITLE
Rats, borked my install completely

### ISSUE THREAD

**Issue by chuck-talk-sp** [tiliado/nuvola-repository-index#5]
I tried to update the flatpak install as Amazon Cloud player was failing, but now I can't get authorized. 
Username: freecode
![fail](https://user-images.githubusercontent.com/5123508/36397171-1ccf6492-1587-11e8-9b9c-8d53f5153bef.png)
I think I have hosed my install completely now.

**Comment by fenryxo** [comment]
Hello @chuck-talk-sp. Could you try following commands?

* `flatpak update --user; flatpak update --system`
* `rm ~/.var/app/eu.tiliado.Nuvola/config/nuvolaruntime/master/config.json`
* `rm ~/.var/app/eu.tiliado.NuvolaAppAmazonCloudPlayer/config/nuvolaruntime/apps_data/amazon_cloud_player/config.json`

**Comment by fenryxo** [comment]
Closing as expired due to inactivity of the reporter.
