### ISSUE TITLE
BBC iPlayer not installing

### ISSUE THREAD

**Issue by RickyS** [tiliado/nuvola-repository-index#7]
$ **flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer**  
error: Remote "nuvola" not found

$ **flatpak --version**  
Flatpak 0.11.3

------------------------------------------------------------------
The Amazon Cloud Player works fine. I'm listening now. I think I updated it but don't see any differences when I run it. How do I tell? I ran this and it said it was updating six things:

$ **flatpak update --system && flatpak update --user**

-----------------------------------------------------------------
Rebooting showed me some quick boxes that indicated the upgrade happened. I'm still not seeing any 'thumbs up' or 'thumbs down'.

**Comment by fenryxo** [comment]
Hello @RickyS. Thanks for reporting your issue.

> The Amazon Cloud Player works fine. I'm listening now. 

If you have already installed Amazon, there is no need to install it again.

> $ flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer
> error: Remote "nuvola" not found

Installation instructions for Ubuntu have changed recently. If you wish to install *new apps*, you need to add [Nuvola Apps Repository](https://nuvola.tiliado.eu/nuvola/ubuntu/xenial/) as the `nuvola` "remote" first.

> I ran this and it said it was updating six things:
> $ flatpak update --system && flatpak update --user

One of them should've been ` eu.tiliado.NuvolaAppAmazonCloudPlayer`. You can see the version in the about dialog (menu → About). It should say Amazon 5.6 & Nuvola 4.10.2 (2-gd534d3e).

> I'm still not seeing any 'thumbs up' or 'thumbs down'.

Thumbs up/down actions are available as tray icon menu entries (see image), Unity launcher quick list menu entries or configurable keyboard shortcuts.

![amazon_thumbs](https://user-images.githubusercontent.com/853706/37269416-7be14eca-25ca-11e8-9c98-6580b1560d56.png)

Having said that, they are inactive in my case. They probably work only for *Amazon Unlimited/Prime Music* subscription.

Please let me know whether I have addressed all your questions.

----

Hello @a-m-s, could you jump in, please? Do you see thumbs up/down action only for *Amazon Unlimited/Prime Music* subscription or are they available also for your own music library? I have no thumbs in my library:

![amazon_library_no_thumbs](https://user-images.githubusercontent.com/853706/37269509-f76114e0-25ca-11e8-9a0f-4ea5fd3b251a.png)

**Comment by RickyS** [comment]
Fixed.
Thanks for your help.
