### ISSUE TITLE
eu.tiliado.NuvolaAppPlex not found

### ISSUE THREAD

**Issue by CodeSurfing145** [tiliado/nuvola-repository-index#9]
I ran the following command after installing the repository and restarting
```
menno@StarDebris-PC:~$ flatpak install nuvola eu.tiliado.NuvolaAppPlex
error: Error searching remote nuvola: Can't find ref eu.tiliado.NuvolaAppPlex
menno@StarDebris-PC:~$ 
```

**Comment by fenryxo** [comment]
Hello @CodeSurfing145. Thanks for reporting this. I accidentally removed Plex Music instead of Groove Music (long gone). It should be fixed now.
